image: $helm_registry_image:$helm_registry_version

variables:
  registry: quay.io
  registry_user: samsung_cnct
  chart_name: zabra
  robot_account: zabra_robot_rw
  helm_registry_image: quay.io/samsung_cnct/helm-registry-agent
  helm_registry_version: v0.7.4-helm_2.6

stages:
  - build
  - test
  - publish

before_script:
  - helm registry login -u ${registry_user}+${robot_account} -p ${REGISTRY_PASSWORD} ${registry}
  # Our helm charts have the version format 'x.x.x-y', where y is the number of commits since the last tagged version.
  # A tagged version's 'y' will be 0.
  # CHART_VER is the 'x.x.x' part of the version. Helm charts may not have a v in their versioning tag.
  # CHART_REL is the 'y' part of the version.
  - export CHART_VER=$(git describe --tags --abbrev=0 2>/dev/null | sed 's/^v//')
  - export CHART_REL=$(git rev-list --count v${CHART_VER}..HEAD 2>/dev/null )

build_chart:
  stage: build
  only:
    - tags
    - branches
  artifacts: 
    paths:
      - ${chart_name}
  script:
    - envsubst < build/Chart.yaml.in > ${chart_name}/Chart.yaml

helm_test:
  stage: test
  only:
    - tags
    - branches
  script:
    - sh build/test.sh

helm_publish_alpha:
  stage: publish
  only:
    - master
  script:
    - cd ${chart_name} && helm registry push ${registry}/${registry_user}/${chart_name} -c alpha

helm_publish_tag:
  stage: publish
  only:
    - /v[0-9]+\.[0-9]+(\.[0-9]+[a-z]?)?/
  script:
    - cd ${chart_name} && helm registry push ${registry}/${registry_user}/${chart_name} -c stable