# Default values.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

name: technical-on-boarding
namespace: technical-on-boarding
image: quay.io/samsung_cnct/technical-on-boarding:1.1.0
host: technical-on-boarding.kubeme.io
