apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{.Values.name}}
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{.Values.name}}
    spec:
      containers:
      - image: {{.Values.image}}
        imagePullPolicy: Always
        name: {{.Values.name}}
        ports:
        - containerPort: 9000
        readinessProbe:
          httpGet:
            path: /version
            port: 9000
          initialDelaySeconds: 15
          timeoutSeconds: 1
        env:
        - name: ONBOARD_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: {{.Values.name}}
              key: ONBOARD_CLIENT_ID
        - name: ONBOARD_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{.Values.name}}
              key: ONBOARD_CLIENT_SECRET
        - name: ONBOARD_ORG
          valueFrom:
            configMapKeyRef:
              name: {{.Values.name}}
              key: ONBOARD_ORG
        - name: ONBOARD_REPO
          valueFrom:
            configMapKeyRef:
              name: {{.Values.name}}
              key: ONBOARD_REPO
