apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
      - image: {{.Values.image}}
        imagePullPolicy: Always
        name: {{ template "fullname" . }}
        ports:
        - containerPort: 9000
        readinessProbe:
          httpGet:
            path: /version
            port: 9000
          initialDelaySeconds: 15
          timeoutSeconds: 1
        env:
        - name: ONBOARD_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: ONBOARD_CLIENT_ID
        - name: ONBOARD_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: ONBOARD_CLIENT_SECRET
        - name: ONBOARD_ORG
          valueFrom:
            configMapKeyRef:
              name: {{ template "fullname" . }}
              key: ONBOARD_ORG
        - name: ONBOARD_REPO
          valueFrom:
            configMapKeyRef:
              name: {{ template "fullname" . }}
              key: ONBOARD_REPO
