apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{.Values.name}}
  namespace: {{.Values.namespace}}
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - {{.Values.host}}
    secretName: technical-on-boarding-tls
  rules:
  - host: {{.Values.host}}
    http:
      paths:
      - path: /
        backend:
          serviceName: technical-on-boarding
          servicePort: 80
