apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
type: Opaque
data:
  ONBOARD_CLIENT_ID: {{default "" .Values.onboard.clientId  | b64enc | quote }}
  ONBOARD_CLIENT_SECRET: {{default "" .Values.onboard.clientSecret | b64enc | quote }}
