apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
type: Opaque
data:
  ONBOARD_CLIENT_ID: {{ .Values.onboard.clientId  | b64enc | quote }}
  ONBOARD_CLIENT_SECRET: {{ .Values.onboard.clientSecret | b64enc | quote }}
